export const initialServices = [
  {
    _id: 'srv_1',
    title: 'Complete Plumbing & Leakage Repair',
    slug: 'plumbing-repair',
    category: 'Plumbing',
    description: 'Expert repair for pipes, leaky faucets, blocked drains, bathroom fittings, and water motor installation.',
    basePrice: 299,
    durationHours: 1.5,
    icon: 'Droplets',
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&q=80&w=800',
    features: ['Pipe leakage fixing', 'Drain unblocking', 'Tap & shower replacement', '30-day warranty'],
    rating: 4.9,
    reviewCount: 142,
    isPopular: true,
  },
  {
    _id: 'srv_2',
    title: 'Home Electrical Wiring & Fixtures',
    slug: 'electrical-wiring',
    category: 'Electrical',
    description: 'Short-circuit fixing, ceiling fan installation, switchboard replacement, fuse box & MCB setup.',
    basePrice: 349,
    durationHours: 1,
    icon: 'Zap',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=800',
    features: ['Short-circuit resolution', 'Fan & light installation', 'Inverter setup', 'Certified safety checks'],
    rating: 4.8,
    reviewCount: 98,
    isPopular: true,
  },
  {
    _id: 'srv_3',
    title: 'AC Deep Service & Gas Refilling',
    slug: 'ac-service',
    category: 'AC Repair',
    description: 'Jet-pump indoor & outdoor AC cleaning, cooling coil check, gas charging, filter sanitization.',
    basePrice: 499,
    durationHours: 2,
    icon: 'Wind',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&q=80&w=800',
    features: ['Foam-jet deep wash', 'Gas leakage check', 'Thermostat testing', '90-day cooling guarantee'],
    rating: 4.95,
    reviewCount: 230,
    isPopular: true,
  },
  {
    _id: 'srv_4',
    title: 'Custom Carpentry & Furniture Repair',
    slug: 'carpentry-service',
    category: 'Carpentry',
    description: 'Door lock replacement, hinge repair, custom modular wardrobe fixing, table and chair restoration.',
    basePrice: 399,
    durationHours: 2.5,
    icon: 'Hammer',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800',
    features: ['Door hinge & lock fixes', 'Wood polishing', 'Custom shelf mounting', 'Precision craftsmanship'],
    rating: 4.7,
    reviewCount: 86,
    isPopular: false,
  },
  {
    _id: 'srv_5',
    title: 'Full House Waterproofing & Painting',
    slug: 'house-painting',
    category: 'Painting',
    description: 'Wall putty, primer application, texture painting, anti-dampness waterproofing coats.',
    basePrice: 1299,
    durationHours: 8,
    icon: 'Paintbrush',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=800',
    features: ['Laser wall inspection', 'Dust-free sanding', 'Premium Asian/Nippon paint', 'Color consultation'],
    rating: 4.9,
    reviewCount: 75,
    isPopular: true,
  },
  {
    _id: 'srv_6',
    title: 'Washing Machine & Refrigerator Repair',
    slug: 'appliance-repair',
    category: 'Appliance Repair',
    description: 'Drum motor repair, PCB diagnostic, cooling issue resolution, microwave oven and RO servicing.',
    basePrice: 399,
    durationHours: 1.5,
    icon: 'Wrench',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&q=80&w=800',
    features: ['Genuine spare parts', 'On-spot diagnostic', 'All top brands supported', 'Transparent bill'],
    rating: 4.85,
    reviewCount: 164,
    isPopular: false,
  },
];

export const initialMistris = [
  {
    _id: 'mst_1',
    fullName: 'Rajesh Kumar Mistri',
    profession: 'Senior Electrician',
    specializations: ['Wiring', 'Fuse Repair', 'Inverter Setup', 'Smart Lights'],
    experienceYears: 9,
    hourlyRate: 350,
    city: 'Mumbai',
    serviceAreas: ['Andheri', 'Bandra', 'Powai', 'Borivali'],
    rating: 4.95,
    reviewCount: 154,
    jobsCompleted: 680,
    isVerified: true,
    isAvailable: true,
    bio: 'Government-certified master electrician with 9+ years of experience across luxury residential societies and commercial offices.',
    avatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?auto=format&fit=crop&q=80&w=300',
    phone: '+91 98201 12345',
  },
  {
    _id: 'mst_2',
    fullName: 'Mohammad Tariq',
    profession: 'Master Plumber',
    specializations: ['Concealed Leakage', 'Water Pressure', 'Sanitary Fittings'],
    experienceYears: 12,
    hourlyRate: 300,
    city: 'Delhi',
    serviceAreas: ['South Delhi', 'Noida', 'Gurugram', 'Lajpat Nagar'],
    rating: 4.9,
    reviewCount: 210,
    jobsCompleted: 920,
    isVerified: true,
    isAvailable: true,
    bio: 'Specialist in concealed leakage detection without wall breaking. Fast, clean, and reliable plumbing work.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300',
    phone: '+91 98110 54321',
  },
  {
    _id: 'mst_3',
    fullName: 'Kishan Sharma',
    profession: 'HVAC & AC Technician',
    specializations: ['Inverter AC', 'Copper Piping', 'Gas Charging', 'Cassette AC'],
    experienceYears: 7,
    hourlyRate: 450,
    city: 'Bengaluru',
    serviceAreas: ['Indiranagar', 'Koramangala', 'HSR Layout', 'Whitefield'],
    rating: 4.88,
    reviewCount: 180,
    jobsCompleted: 540,
    isVerified: true,
    isAvailable: true,
    bio: 'Daikin & Voltas trained AC service technician specializing in jet cleaning, leak fixing, and PCB repairs.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300',
    phone: '+91 99887 76655',
  },
  {
    _id: 'mst_4',
    fullName: 'Rameshwar Vishwakarma',
    profession: 'Expert Carpenter',
    specializations: ['Modular Kitchens', 'Wooden Flooring', 'Locks & Latches', 'Furniture Polishing'],
    experienceYears: 15,
    hourlyRate: 400,
    city: 'Pune',
    serviceAreas: ['Kothrud', 'Viman Nagar', 'Baner', 'Wakad'],
    rating: 4.92,
    reviewCount: 165,
    jobsCompleted: 810,
    isVerified: true,
    isAvailable: true,
    bio: 'Heritage carpenter specializing in solid teak wood restorations, modular fittings, and custom cabinet assemblies.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300',
    phone: '+91 97654 32109',
  },
];

export const initialBookings = [
  {
    _id: 'bok_101',
    customer: {
      name: 'Amit Patel',
      email: 'amit@example.com',
      phone: '+91 98765 00001',
    },
    service: initialServices[0],
    mistri: initialMistris[1],
    bookingDate: '2026-09-15',
    timeSlot: '11:00 AM - 01:00 PM',
    serviceAddress: {
      fullName: 'Amit Patel',
      phone: '+91 98765 00001',
      street: 'Flat 402, Sunshine Heights',
      city: 'Mumbai',
      pincode: '400053',
      landmark: 'Near Metro Station',
    },
    problemDescription: 'Bathroom pipe is leaking underneath the wash basin.',
    amount: 299,
    paymentMethod: 'Cash on Service',
    paymentStatus: 'Pending',
    status: 'Confirmed',
    createdAt: new Date().toISOString(),
  },
];
