/**
 * MISTRI – SEEDER DATASET
 * Empty production-ready service & technician initial datasets.
 */

export const initialServices = [];
export const initialMistris = [];
export const initialBookings = [];

export const initialProducts = [
  {
    id: 'prod_101',
    name: 'UltraTech Super Cement 50kg',
    slug: 'ultratech-super-cement-50kg',
    category: 'Cement & Concrete',
    categorySlug: 'cement',
    section: 'Civil & Construction',
    brand: 'UltraTech',
    unit: '50 kg Bag',
    description: 'PPC Grade high-strength premium cement suitable for all civil construction works.',
    price: 380,
    mrp: 420,
    stockCount: 500,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=600',
    gallery: ['https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=600'],
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'prod_102',
    name: 'CenturyPly 710 Commercial Plywood 18mm',
    slug: 'centuryply-710-commercial-plywood-18mm',
    category: 'Plywood & Boards',
    categorySlug: 'plywood-mdf-hdhmr',
    section: 'Woodwork & Furniture',
    brand: 'CenturyPly',
    unit: '8x4 ft Sheet',
    description: 'Water resistant BWP grade plywood for interior & exterior carpentry.',
    price: 2450,
    mrp: 2900,
    stockCount: 120,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600',
    gallery: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600'],
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'prod_103',
    name: 'Tata Tiscon 550SD TMT Rebar Steel 12mm',
    slug: 'tata-tiscon-550sd-tmt-rebar-steel-12mm',
    category: 'Steel & Rebars',
    categorySlug: 'steel-rebars',
    section: 'Civil & Construction',
    brand: 'Tata Tiscon',
    unit: 'Piece (12m)',
    description: 'High-ductility earthquake resistant Fe550D grade steel rebars for RCC structures.',
    price: 680,
    mrp: 750,
    stockCount: 350,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=600',
    gallery: ['https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=600'],
    isFeatured: true,
    isPopular: true,
  },
  {
    id: 'prod_104',
    name: 'Asian Paints Royale Luxury Emulsion White 20L',
    slug: 'asian-paints-royale-luxury-emulsion-white-20l',
    category: 'Paints & Wall Finishes',
    categorySlug: 'paints-coatings',
    section: 'Painting & Decor',
    brand: 'Asian Paints',
    unit: '20 Litre Bucket',
    description: 'Teflon surface protected washable interior wall paint with soft sheen finish.',
    price: 5800,
    mrp: 6500,
    stockCount: 85,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=600',
    gallery: ['https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=600'],
    isFeatured: true,
    isPopular: false,
  },
  {
    id: 'prod_105',
    name: 'Kajaria Premium Vitrified Floor Tiles 600x600mm',
    slug: 'kajaria-vitrified-floor-tiles-600x600mm',
    category: 'Tiles & Flooring',
    categorySlug: 'tiles-flooring',
    section: 'Flooring & Finishes',
    brand: 'Kajaria',
    unit: 'Box (4 Tiles / 15.5 sq ft)',
    description: 'Double charged stain-resistant high gloss vitrified tiles for living rooms.',
    price: 950,
    mrp: 1200,
    stockCount: 200,
    inStock: true,
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    gallery: ['https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600'],
    isFeatured: false,
    isPopular: true,
  },
];

export const initialCategorySections = [
  {
    id: 'sec_101',
    title: 'Civil & Construction',
    slug: 'civil-construction',
    description: 'Raw building supplies including cement, steel rebars, aggregates and bricks.',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&q=80&w=600',
    isActive: true,
  },
  {
    id: 'sec_102',
    title: 'Woodwork & Furniture',
    slug: 'woodwork-furniture',
    description: 'Commercial plywood, MDF, HDHMR boards and laminates.',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600',
    isActive: true,
  },
  {
    id: 'sec_103',
    title: 'Painting & Decor',
    slug: 'painting-decor',
    description: 'Interior and exterior paints, primers, wall putties and waterproofing chemicals.',
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=600',
    isActive: true,
  },
  {
    id: 'sec_104',
    title: 'Flooring & Finishes',
    slug: 'flooring-finishes',
    description: 'Vitrified tiles, ceramic wall tiles, granite slabs and wooden flooring.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    isActive: true,
  },
];

export const initialCategories = [
  {
    id: 'cat_101',
    name: 'Cement & Concrete',
    slug: 'cement',
    section: 'Civil & Construction',
    description: 'OPC, PPC and weather-proof cement bags from top manufacturers.',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=600',
    subcategories: ['PPC Cement', 'OPC 53 Grade Cement', 'White Cement', 'Ready Mix Concrete'],
    isActive: true,
  },
  {
    id: 'cat_102',
    name: 'Plywood & Boards',
    slug: 'plywood-mdf-hdhmr',
    section: 'Woodwork & Furniture',
    description: 'Waterproof plywood, blockboards, MDF sheets and HDHMR panels.',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600',
    subcategories: ['Commercial Plywood', 'BWP Marine Plywood', 'HDHMR Board', 'Acrylic Sheets'],
    isActive: true,
  },
  {
    id: 'cat_103',
    name: 'Steel & Rebars',
    slug: 'steel-rebars',
    section: 'Civil & Construction',
    description: 'Fe550 and Fe550D TMT rebars, binding wire and structural steel channels.',
    image: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=600',
    subcategories: ['8mm TMT Steel', '10mm TMT Steel', '12mm TMT Steel', 'Binding Wire'],
    isActive: true,
  },
  {
    id: 'cat_104',
    name: 'Paints & Wall Finishes',
    slug: 'paints-coatings',
    section: 'Painting & Decor',
    description: 'Emulsions, enamels, acrylic wall putties and waterproofing coats.',
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&q=80&w=600',
    subcategories: ['Interior Emulsion', 'Exterior Emulsion', 'Wall Putty', 'Waterproofing Coating'],
    isActive: true,
  },
  {
    id: 'cat_105',
    name: 'Tiles & Flooring',
    slug: 'tiles-flooring',
    section: 'Flooring & Finishes',
    description: 'Vitrified floor tiles, bathroom wall tiles, marble slabs and tile adhesive.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600',
    subcategories: ['Vitrified Floor Tiles', 'Ceramic Wall Tiles', 'Tile Adhesive', 'Epoxy Grout'],
    isActive: true,
  },
];


