import mongoose from 'mongoose';

const { Mixed } = mongoose.Schema.Types;

/**
 * Builds a model for a record the storefront/admin app owns.
 *
 * Records are addressed by a string business key (e.g. `id: "cat_1726..."`, a coupon
 * `code`) generated by the app, so the key is unique and required. The listed fields
 * document the expected shape; `strict: false` keeps any extra field the admin panel
 * adds so nothing it saves is silently dropped.
 */
export const createAppModel = (name, { key = 'id', fields = {}, collection } = {}) => {
  if (mongoose.models[name]) return mongoose.models[name];

  const schema = new mongoose.Schema(
    {
      [key]: { type: String, required: true, unique: true, trim: true },
      ...fields,
    },
    {
      strict: false,
      minimize: false,
      versionKey: false,
      collection,
    }
  );

  schema.set('toJSON', {
    transform: (_doc, ret) => {
      delete ret._id;
      return ret;
    },
  });

  const model = mongoose.model(name, schema);
  model.appKey = key;
  return model;
};

export { Mixed };
